#!/bin/bash
if [ -z "$PYFILE" ];
then
	echo "Error: PYFILE environemnt variable is not set."
	exit 1
fi

echo "Compiling main.py  ..."
python3 -m py_compile "$PYFILE"

mv __pycache__/"${PYFILE%.*}".*.pyc "${PYFILE}c"

rmdir __pycache__ 2> /dev/null
